Repository aztfmod/rover, pull requests merged in 2021-05, with the labels that each got.

#149 Update for Azure Devops - AKS
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .env
  .github/workflows/rover-ci.yml
  .gitignore
  .shellspec
  Dockerfile
  Makefile
  agents/azure_devops/azdo.sh
  docs/CONTINOUS_INTEGRATION.md
  docs/DEV_CONTAINER.md
  docs/USAGE.md
  docs/symphony/sample.symphony.yaml
  scripts/.kubectl_aliases
  scripts/build_image.sh
  scripts/ci.sh
  scripts/ci_tasks/terraform-format.yml
  scripts/ci_tasks/terraform-plan.yml
  scripts/ci_tasks/terraform-validate.yml
  scripts/ci_tasks/tflint.yml
  scripts/functions.sh
  scripts/rover.sh
  scripts/symphony_yaml.sh
  scripts/task.sh
  scripts/tfstate_azurerm.sh
  scripts/zsh-autosuggestions.zsh
  spec/harness/ci_tasks/task1.yml
  spec/harness/ci_tasks/task2.yml
  spec/harness/ci_tasks/task3.yml
  spec/harness/symphony.yml
  spec/spec_helper.sh
  spec/unit/README.md
  spec/unit/ci_spec.sh
  spec/unit/symphony_spec.sh
  spec/unit/task_spec.sh
Labels: enhancement

#151 Fix regression system msi
  scripts/functions.sh
Labels: bug

#152 rover ci can run for only a single level
  .devcontainer/devcontainer.json
  Dockerfile
  scripts/ci.sh
  scripts/functions.sh
  scripts/task.sh
  spec/unit/ci_spec.sh
Labels: tools/terraform

#150 Udpdate to TF 15.3
  .devcontainer/devcontainer.json
  .env.terraform
  Dockerfile
  README.md
  scripts/ci.sh
  scripts/functions.sh
  scripts/task.sh
  spec/unit/ci_spec.sh
Labels: dependencies, documentation

#156 Add soveregin cloud endpoints and suffix environment variables (part 1)
  scripts/functions.sh
Labels: enhancement

#154 Update ubuntu to 21.04 + multi-layers
  .env
  .env.terraform
  .github/workflows/rover-ci.yml
  Dockerfile
  Makefile
  agents/.env
  changelog.md
  docs/CONTINOUS_INTEGRATION.md
  docs/USAGE.md
  docs/symphony/sample.symphony.yaml
  scripts/banner.sh
  scripts/build_image.sh
  scripts/clone.sh
  scripts/functions.sh
  scripts/symphony_yaml.sh
  scripts/task.sh
  scripts/tfc.sh
  scripts/zsh-autosuggestions.zsh
Labels: enhancement
