Repository aztfmod/rover, pull requests merged in 2021-12, with the labels that each got.

#222 declare tf_plan_file as local in terraform functions
  scripts/tfstate.sh
Labels: bug

#215 Replaced 'az keyvault list' with 'az graph query'
  .env
  Dockerfile
  scripts/functions.sh
Labels: enhancement

#225 Add support for 'terraform show'
  scripts/functions.sh
  scripts/rover.sh
  scripts/tfstate.sh
Labels: enhancement

#223 December Update
  .env
  .env.terraform
  .vscode/settings.json
  Dockerfile
  rover_on_ssh_host.yml
  scripts/backend.azurerm.tf
  scripts/functions.sh
  scripts/rover.sh
  scripts/tfstate.sh
Labels: bug, enhancement

#229 Quick fix - december update
  Dockerfile
Labels: bug
