Repository aztfmod/rover, pull requests merged in 2021-06, with the labels that each got.

#157 Add support for Rover test
  scripts/functions.sh
  scripts/rover.sh
  scripts/test_runner.sh
  scripts/tfstate_azurerm.sh
Labels: enhancement

#163 Integration June 2021
  .devcontainer/docker-compose.yml
  .env
  .env.terraform
  .pre-commit-config.yaml
  Dockerfile
  docker-compose.yml
Labels: bug, enhancement

#167 Update for TF1.0.0 and missing test_runner.sh
  Dockerfile
  scripts/tfstate_azurerm.sh
Labels: bug

#170 Fix master
  Dockerfile
  scripts/functions.sh
  scripts/tfstate_azurerm.sh
Labels: enhancement

#171 Add rover login ----impersonate-sp-from-keyvault-url + fix terraform return code
  .gitignore
  scripts/functions.sh
  scripts/rover.sh
  scripts/tfstate_azurerm.sh
Labels: bug, enhancement

#173 Manual workflow triggering for rover dev builds
  .github/workflows/rover-preview.yml
Labels: enhancement

#174 Install Vault in rover
  Dockerfile
Labels: enhancement

#175 Patch vault installation
  Dockerfile
Labels: enhancement

#178 Check env values - empty path
  scripts/functions.sh
  scripts/rover.sh
Labels: bug, enhancement

#180 Removed --subscription as not part of the az ad sp show command
  scripts/functions.sh
Labels: bug

#179 Fix condition for keyvault
  Dockerfile
  scripts/rover.sh
Labels: bug

#183 Update for dependencies management
  Dockerfile
Labels: dependencies

#187 Update return code value
  scripts/tfstate_azurerm.sh
Labels: bug

#188 Fix a return code
  scripts/functions.sh
  scripts/tfstate_azurerm.sh
Labels: bug

#189 Update Vault deployment
  .env
  Dockerfile
  docker-compose.yml
Labels: bug
