Repository aztfmod/rover, pull requests merged in 2022-06, with the labels that each got.

#254 Initial support for TFC-TFE remote backend type
  .devcontainer/.zshrc
  .env.terraform
  Dockerfile
  agents/tfc/Dockerfile
  docker-bake.override.hcl
  scripts/banner.sh
  scripts/functions.sh
  scripts/lib/aad_constants.sh
  scripts/lib/azure_ad.sh
  scripts/lib/bootstrap.sh
  scripts/lib/github.com.sh
  scripts/lib/terraform.sh
  scripts/lib/tfcloud.sh
  scripts/parse_command.sh
  scripts/remote.sh
  scripts/rover.sh
  scripts/terraform-enterprise-push.sh
  scripts/tfc.sh
  scripts/tfstate.sh
Labels: enhancement

#263 Fix an issue on rover login
  scripts/functions.sh
Labels: bug

#265 Do not configure remote backend for launchpad
  scripts/functions.sh
Labels: bug

#266 Update ARM_USE_MSAL defaults
  scripts/rover.sh
Labels: bug

#268 Updated Impersonate function to fix a breaking change.
  scripts/functions.sh
Labels: bug

#269 Adding TF updates and dnsutils
  .env.terraform
  Dockerfile
  scripts/lib/bootstrap.sh
Labels: tools/version
